enum SETTING {
    ALLOWED_FILES = "ALLOWED_FILES",
    ALLOWED_FILES_ZIP = "ALLOWED_FILES_ZIP",
    ALLOWED_HEADERS = "ALLOWED_HEADERS",
    ALLOWED_HEADERS_ZIP = "ALLOWED_HEADERS_ZIP",
}

export default SETTING;
