import { MigrationInterface, QueryRunner } from "typeorm";

export class AddIndex1734392610692 implements MigrationInterface {
    name = 'AddIndex1734392610692'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_e6fda8f8b236cecaf1ff5f73a7"`);
        await queryRunner.query(`CREATE TABLE "temporary_submission_model" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "wadName" varchar NOT NULL, "wadURL" text, "wadLevel" varchar NOT NULL, "wadEngine" integer NOT NULL, "gzDoomActions" text, "submitterName" text, "submitterAuthor" boolean NOT NULL DEFAULT (0), "distributable" boolean NOT NULL DEFAULT (0), "info" text, "submissionRoundId" integer NOT NULL, "playOrder" integer, "customWadFileName" text, "youtubeLink" text, "submitterEmail" varchar NOT NULL, "submissionValid" boolean NOT NULL DEFAULT (0), "isChosen" boolean NOT NULL DEFAULT (0), "verified" boolean NOT NULL DEFAULT (0), "recordedFormat" text NOT NULL DEFAULT ('Practised'), "playTestEngine" varchar, CONSTRAINT "FK_b326b4d8fcc9cb80b8f50849b23" FOREIGN KEY ("submissionRoundId") REFERENCES "submission_round_model" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
        await queryRunner.query(`INSERT INTO "temporary_submission_model"("id", "createdAt", "updatedAt", "wadName", "wadURL", "wadLevel", "wadEngine", "gzDoomActions", "submitterName", "submitterAuthor", "distributable", "info", "submissionRoundId", "playOrder", "customWadFileName", "youtubeLink", "submitterEmail", "submissionValid", "isChosen", "verified", "recordedFormat", "playTestEngine") SELECT "id", "createdAt", "updatedAt", "wadName", "wadURL", "wadLevel", "wadEngine", "gzDoomActions", "submitterName", "submitterAuthor", "distributable", "info", "submissionRoundId", "playOrder", "customWadFileName", "youtubeLink", "submitterEmail", "submissionValid", "isChosen", "verified", "recordedFormat", "playTestEngine" FROM "submission_model"`);
        await queryRunner.query(`DROP TABLE "submission_model"`);
        await queryRunner.query(`ALTER TABLE "temporary_submission_model" RENAME TO "submission_model"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e6fda8f8b236cecaf1ff5f73a7" ON "submission_model" ("submissionRoundId", "submitterEmail") `);
        await queryRunner.query(`DROP INDEX "IDX_e6fda8f8b236cecaf1ff5f73a7"`);
        await queryRunner.query(`CREATE TABLE "temporary_submission_model" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "wadName" varchar NOT NULL, "wadURL" text, "wadLevel" varchar NOT NULL, "wadEngine" integer NOT NULL, "gzDoomActions" text, "submitterName" text, "submitterAuthor" boolean NOT NULL DEFAULT (0), "distributable" boolean NOT NULL DEFAULT (0), "info" text, "submissionRoundId" integer NOT NULL, "playOrder" integer, "customWadFileName" text, "youtubeLink" text, "submitterEmail" varchar NOT NULL, "submissionValid" boolean NOT NULL DEFAULT (0), "isChosen" boolean NOT NULL DEFAULT (0), "verified" boolean NOT NULL DEFAULT (0), "recordedFormat" text NOT NULL DEFAULT ('Practised'), "playTestEngine" text, CONSTRAINT "FK_b326b4d8fcc9cb80b8f50849b23" FOREIGN KEY ("submissionRoundId") REFERENCES "submission_round_model" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
        await queryRunner.query(`INSERT INTO "temporary_submission_model"("id", "createdAt", "updatedAt", "wadName", "wadURL", "wadLevel", "wadEngine", "gzDoomActions", "submitterName", "submitterAuthor", "distributable", "info", "submissionRoundId", "playOrder", "customWadFileName", "youtubeLink", "submitterEmail", "submissionValid", "isChosen", "verified", "recordedFormat", "playTestEngine") SELECT "id", "createdAt", "updatedAt", "wadName", "wadURL", "wadLevel", "wadEngine", "gzDoomActions", "submitterName", "submitterAuthor", "distributable", "info", "submissionRoundId", "playOrder", "customWadFileName", "youtubeLink", "submitterEmail", "submissionValid", "isChosen", "verified", "recordedFormat", "playTestEngine" FROM "submission_model"`);
        await queryRunner.query(`DROP TABLE "submission_model"`);
        await queryRunner.query(`ALTER TABLE "temporary_submission_model" RENAME TO "submission_model"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e6fda8f8b236cecaf1ff5f73a7" ON "submission_model" ("submissionRoundId", "submitterEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_a36f9397105bb9b8c0c79f86a1" ON "submission_round_model" ("id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_a36f9397105bb9b8c0c79f86a1"`);
        await queryRunner.query(`DROP INDEX "IDX_e6fda8f8b236cecaf1ff5f73a7"`);
        await queryRunner.query(`ALTER TABLE "submission_model" RENAME TO "temporary_submission_model"`);
        await queryRunner.query(`CREATE TABLE "submission_model" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "wadName" varchar NOT NULL, "wadURL" text, "wadLevel" varchar NOT NULL, "wadEngine" integer NOT NULL, "gzDoomActions" text, "submitterName" text, "submitterAuthor" boolean NOT NULL DEFAULT (0), "distributable" boolean NOT NULL DEFAULT (0), "info" text, "submissionRoundId" integer NOT NULL, "playOrder" integer, "customWadFileName" text, "youtubeLink" text, "submitterEmail" varchar NOT NULL, "submissionValid" boolean NOT NULL DEFAULT (0), "isChosen" boolean NOT NULL DEFAULT (0), "verified" boolean NOT NULL DEFAULT (0), "recordedFormat" text NOT NULL DEFAULT ('Practised'), "playTestEngine" varchar, CONSTRAINT "FK_b326b4d8fcc9cb80b8f50849b23" FOREIGN KEY ("submissionRoundId") REFERENCES "submission_round_model" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
        await queryRunner.query(`INSERT INTO "submission_model"("id", "createdAt", "updatedAt", "wadName", "wadURL", "wadLevel", "wadEngine", "gzDoomActions", "submitterName", "submitterAuthor", "distributable", "info", "submissionRoundId", "playOrder", "customWadFileName", "youtubeLink", "submitterEmail", "submissionValid", "isChosen", "verified", "recordedFormat", "playTestEngine") SELECT "id", "createdAt", "updatedAt", "wadName", "wadURL", "wadLevel", "wadEngine", "gzDoomActions", "submitterName", "submitterAuthor", "distributable", "info", "submissionRoundId", "playOrder", "customWadFileName", "youtubeLink", "submitterEmail", "submissionValid", "isChosen", "verified", "recordedFormat", "playTestEngine" FROM "temporary_submission_model"`);
        await queryRunner.query(`DROP TABLE "temporary_submission_model"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e6fda8f8b236cecaf1ff5f73a7" ON "submission_model" ("submissionRoundId", "submitterEmail") `);
        await queryRunner.query(`DROP INDEX "IDX_e6fda8f8b236cecaf1ff5f73a7"`);
        await queryRunner.query(`ALTER TABLE "submission_model" RENAME TO "temporary_submission_model"`);
        await queryRunner.query(`CREATE TABLE "submission_model" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "wadName" varchar NOT NULL, "wadURL" text, "wadLevel" varchar NOT NULL, "wadEngine" integer NOT NULL, "gzDoomActions" text, "submitterName" text, "submitterAuthor" boolean NOT NULL DEFAULT (0), "distributable" boolean NOT NULL DEFAULT (0), "info" text, "submissionRoundId" integer NOT NULL, "playOrder" integer, "customWadFileName" text, "youtubeLink" text, "submitterEmail" varchar NOT NULL, "submissionValid" boolean NOT NULL DEFAULT (0), "isChosen" boolean NOT NULL DEFAULT (0), "verified" boolean NOT NULL DEFAULT (0), "recordedFormat" text NOT NULL DEFAULT ('Practised'), "playTestEngine" varchar, CONSTRAINT "FK_b326b4d8fcc9cb80b8f50849b23" FOREIGN KEY ("submissionRoundId") REFERENCES "submission_round_model" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
        await queryRunner.query(`INSERT INTO "submission_model"("id", "createdAt", "updatedAt", "wadName", "wadURL", "wadLevel", "wadEngine", "gzDoomActions", "submitterName", "submitterAuthor", "distributable", "info", "submissionRoundId", "playOrder", "customWadFileName", "youtubeLink", "submitterEmail", "submissionValid", "isChosen", "verified", "recordedFormat", "playTestEngine") SELECT "id", "createdAt", "updatedAt", "wadName", "wadURL", "wadLevel", "wadEngine", "gzDoomActions", "submitterName", "submitterAuthor", "distributable", "info", "submissionRoundId", "playOrder", "customWadFileName", "youtubeLink", "submitterEmail", "submissionValid", "isChosen", "verified", "recordedFormat", "playTestEngine" FROM "temporary_submission_model"`);
        await queryRunner.query(`DROP TABLE "temporary_submission_model"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e6fda8f8b236cecaf1ff5f73a7" ON "submission_model" ("submissionRoundId", "submitterEmail") `);
    }

}
